extends Control
class_name MonsterList

@onready var monster_list_entry_container: MarginContainer = $MarginContainer/PanelContainer/VBoxContainer/MonsterListEntryContainer
@onready var monster_list_entry = preload("res://ui/ingame_menu/party_list_entry.tscn")

func _ready() -> void:
	visible = false

func _on_close_button_pressed() -> void:
	visible = false
	pass # Replace with function body.

func update() -> void:
	pass
	
func _update_monster_list() -> void:
	print("update list")
	for i in SaveManager.current_save.party.size():
		var monster = SaveManager.current_save.party[i]
		var entry = monster_list_entry.instantiate()
		
		# populate the new entry
		entry.populate(monster)
		
		# add it to the list
		monster_list_entry_container.add_child(entry)

func _update_player_info() -> void:
	#%PlayerName.text = 
	pass
